### ISSUE TITLE
Crash On Startup

### ISSUE THREAD

**Issue by ChloeDawn** [shadowfacts/WaypointCompass#1]
**Mod version:** [1.11-1.0.1](https://minecraft.curseforge.com/projects/waypoint-compass/files/2362868)
**Crash report:** [crash-2017-02-19_15.57.24-client.txt](https://gist.github.com/409cb099a4b8bd0cc48d864ab1f59b0e)

(World should always be nullable in recipes.)

**Comment by shadowfacts** [comment]
Fixed in 1.0.2 for MC [1.10.2](https://minecraft.curseforge.com/projects/waypoint-compass/files/2383746) and [1.11.2](https://minecraft.curseforge.com/projects/waypoint-compass/files/2383747)
